export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const CREATE_WORKOUT_SUCCESS = 'CREATE_WORKOUT_SUCCESS';
export const CREATE_WORKOUT_FAIL = 'CREATE_WORKOUT_FAIL';
export const CREATE_WORKOUT_REQUESTED = 'CREATE_WORKOUT_REQUESTED';
